### ISSUE TITLE
Please comment on this issue to be added as a collaborator.

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/intro-github-am#1]
Tell us -- where are you originally from?

**Comment by hollenberry** [comment]
San Diego!

**Comment by ahu2012** [comment]
DC

**Comment by learnereveryday** [comment]
Beijing, China.

**Comment by sarah-schroeder** [comment]
San Diego (also)

**Comment by alanzhong** [comment]
toronto

**Comment by mmanfred** [comment]
NY

**Comment by XuboS** [comment]
New York!

**Comment by githubteacher** [comment]
:tada: @hollenberry, @ahu2012, @learnereveryday, @sarah-schroeder, @alanzhong, @mmanfred, and @XuboS are now  repository collaborators. :balloon:

**Comment by hollenberry** [comment]
@githubteacher come back!

**Comment by tengso** [comment]
hello

**Comment by githubteacher** [comment]
:tada: @tengso is now a repository collaborator. :balloon:
